import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Header from '../compont/Header'
export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
      </Head>
      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
                <Link href="/add" className="add">add project</Link> 
        </h1>
        <section >
          {props.lists.map(list =>
            <article key={list.dirId}>
              <img src={list.image} alt={list.name} /> 
              <h3>{list.category}</h3>
              <div className="price"> {list.price} USD</div>
               {/* make link post/name  */}
              <Link href={`/post/${list.name}`}>
                <h2>{list.name}</h2>
              </Link>
              <div className="addToCard"> {list.stock} add to card</div>
            </article>
          )}
        </section>
      </main>
    </div>

  )
}


export async function getStaticProps() {
  const res = await fetch('http://localhost:8080/api/products')
  const lists = await res.json()

  return {
    props: {
      lists: lists
    }
  }
}
