import Head from 'next/head'
import Image from 'next/image'
import Header from '../compont/Header'

import { useEffect } from 'react'

export default function Form() { 
    //  login auth http://localhost:8080/api/users/signin by POST 
    useEffect(() => {
        // setter
        localStorage.setItem('myData', 'data');
        // getter
        localStorage.getItem('myData');
        console.log(localStorage.getItem('myData'));
    }, [])
    

   let signin = (e) => {
        e.preventDefault();
        const data = {
            email: e.target.email.value,
            password_digest: e.target.password_digest.value
        }
        fetch('http://localhost:8080/api/signin', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        })
            .then(res => res.json())
            .then(res => {
                window.localStorage.setItem("token", JSON.stringify(res));

                console.log(res)
                window.location.href = '/';
            })
    }
        
    
    return (
        < div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>

            </Head>
            <Header /> 
      <form onSubmit={signin}> 
            <div className="form-group">
                <label htmlFor="email">Email</label>
                <input type="email" className="form-control" id="email" placeholder="Enter email"/>
            </div>
            <div className="form-group">
                <label htmlFor="password_digest">password_digest</label>
                <input type="password" className="form-control" id="password_digest" placeholder="Enter password_digest"/>
            </div>
            <button type="submit" className="btn btn-primary">Submit</button>

      </form>
    </div >
    )
  }