import Head from 'next/head'
import Image from 'next/image'
import Header from '../compont/Header'

import { useEffect } from 'react'

export default function Form() {
    //  register auth http://localhost:8080/api/users by POST  
    //  login auth http://localhost:8080/api/users/login by POST
    //  logout http://localhost:8080/api/users/logout by POST
    //  get user http://localhost:8080/api/users/me by GET
    useEffect(() => {
        // setter
        localStorage.setItem('myData', 'data');
        // getter
        localStorage.getItem('myData');
        console.log(localStorage.getItem('myData'));
    }, [])
    

   let registerUser = (e) => {
        e.preventDefault();
        const data = {
            name: e.target.name.value,
            email: e.target.email.value,
            password_digest: e.target.password_digest.value
        }
        fetch('http://localhost:8080/api/users', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        })
            .then(res => res.json())
            .then(res => {
                window.localStorage.setItem("token", JSON.stringify(res));
                // redirect to login page
                window.location.href = '/';
            }).then(res => {
                console.log(res)
            })
    }
    
    return (
        < div >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
                
            </Head>
            <Header /> 
      <form onSubmit={registerUser}> 
            <div className="form-group">
                <label htmlFor="name">Name</label>
                <input type="text" className="form-control" id="name" placeholder="Enter name"/>
            </div>
            <div className="form-group">
                <label htmlFor="email">Email</label>
                <input type="email" className="form-control" id="email" placeholder="Enter email"/>
            </div>
            <div className="form-group">
                <label htmlFor="password_digest">password_digest</label>
                <input type="password_digest" className="form-control" id="password_digest" placeholder="Enter password_digest"/>
            </div>
            <button type="submit" className="btn btn-primary">Submit</button>

      </form>
    </div >
    )
  }