import { useRouter } from 'next/router'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import Header from '../../compont/Header'
export default function Home(props) {
  const router = useRouter()
  const { id } = router.query
  // GET fetch by body id
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous" />
      </Head>
      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
        < h1 > {props.lists.name} </h1 > 
        </h1>
        <section > 
            <article >
              <img src={props.lists.image} alt={props.lists.name} /> 
              <h3>{props.lists.category}</h3>
              <div className="price"> {props.lists.price} USD</div> 
               < h2 > {props.lists.name} </h2 >
              <div className="addToCard"> {props.lists.stock} add to card</div>
            </article> 
        </section>
      </main>
    </div>

  )
}

export async function getServerSideProps(context) {
  const res = await fetch(`http://localhost:8080/api/products/post/${context.query.id}`)
  const lists = await res.json()
console.log(lists);
  return {
    props: {
      lists: lists
    }
  }
}

